name: Merge master to dev

on:
    push:
        branches:
            - master

jobs:
    merge-master-to-dev:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: devmasx/merge-branch@master
              with:
                  type: now
                  head_to_merge: master
                  target_branch: dev
                  message: 'chore: merge master to dev'
                  github_token: ${{ secrets.GH_TOKEN }}
