name: Update zigbee-herdsman-converters
on:
  repository_dispatch:
    types: update_zhc

jobs:
  update_zhc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: dev
    - uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    - run: npm install zigbee-herdsman-converters@${{ github.event.client_payload.version }} --save-exact
    - run: rm -rf node_modules npm-shrinkwrap.json && npm install && npm shrinkwrap --dev
    - uses: peter-evans/create-pull-request@v2
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
      with:
        commit-message: Update zigbee-herdsman-converters to ${{ github.event.client_payload.version }}
        branch: "update_zhc"
        title: Update zigbee-herdsman-converters
